### ISSUE TITLE
RANSAC

### ISSUE THREAD

**Issue by BrunoSanchez** [toros-astro/astroalign#13]
Found an example where the results aren't symmetric , i.e., the result of aligning an image A to  image B works fine, but  aligning  B to A isn't converging. RANSAC is involved in the stacktrace error. Doing some research about RANSAC found this package scikitimage where it uses RANSAC and seems quite tested. Is there a way to test the results of ransac from here vs RANSAC from sickitimage.

**Comment by martinberoiz** [comment]
This may have to do with #7

**Comment by BrunoSanchez** [comment]
Yes, in fact I already made a push, modifyng some options to align_image,
so now it can receive the desired number of sources used for reference and
test.
This once properly settled performs well. (In fact I obtained a great
alignation).
Things like this now are valid:
´´´
mlaligned = astroalign.align.align_image(ml, mr, n_test_src=50,
n_ref_src=50, px_tol=2.)
´´´


2016-04-21 12:24 GMT-03:00 Martin Beroiz <notifications@github.com>:
