### ISSUE TITLE
implement piecewise warp instead of rigid transformation

### ISSUE THREAD

**Issue by martinberoiz** [toros-astro/astroalign#16]
Use [``skimage.transform.PiecewiseAffineTransform``](http://scikit-image.org/docs/stable/api/skimage.transform.html#skimage.transform.warp) to warp the image to fit star positions better.

**Comment by BrunoSanchez** [comment]
what if the rotation angle is reaaally close to zero?
Does it performs transformation at all?

**Comment by martinberoiz** [comment]
If rotation angle is really small, it may perform the calculations but effectively not modifying the pixel values. The bicubic interpolation with the identity transformation may or may not modify the pixel values. I haven't tested that situation.

**Comment by martinberoiz** [comment]
maybe [``skimage.transform.PolynomialTransform``](http://scikit-image.org/docs/stable/api/skimage.transform.html#skimage.transform.PolynomialTransform) works better
