### ISSUE TITLE
attempting to align using coordinates fails

### ISSUE THREAD

**Issue by BrunoSanchez** [toros-astro/astroalign#21]
The function `find_transform(source_list, target_list)` won't work when the lists are drawn straight from a sep catalog:

```ns = sep_source_cat[['x', 'y']]
rs =  sep_targ_cat[['x', 'y']]
aa.find_transform(ns, rs)
```
raises `ValueError need more than one value to unpack`

Instead a reconstruction of these coordinates lists would fix the problem:

```ns =  np.empty((len(sep_source_cat, 2))
j=0
for x, y in sep_source_cat[['x', 'y']]:
   ns[j] = x, y
   j += 1
```

**Comment by martinberoiz** [comment]
I tracked down the problem and it fails because `rs`'s shape is (N, ) instead of (N, 2). I have to think more to find a fix for it.

**Comment by martinberoiz** [comment]
A quick fix for now would be to expand

    rs =  [(x, y) for x, y in sep_targ_cat[['x', 'y']]]
