### ISSUE TITLE
Citation for Astroalign

### ISSUE THREAD

**Issue by ilmimris** [toros-astro/astroalign#23]
I want to cite this work for my thesis, could you make it possible by using figshare or zenodo? 
I found a nice article about that: https://guides.github.com/activities/citable-code/

**Comment by martinberoiz** [comment]
Thank you, yes you can.

That seems like a great idea, thank you for pointing that out. I'll take a look and will possibly implement this by today.

**Comment by ilmimris** [comment]
Thank you.
