### ISSUE TITLE
No Issue!

### ISSUE THREAD

**Issue by mworion** [toros-astro/astroalign#32]
Hi Martin,

I looked to astroalign with much interest. You mention that astroalign take ideas from astrometry.net. As I currently building some astronomy software as well, I look for a stacking algorithm like yours, but for FITS Images, which already have distortion parameters from astrometry.net In this case many of the calculation should be already done. Is that right ? Could you point me in the direction, how to find a solution with WCS Headers ?

Thanks for your help !

Michel

**Comment by martinberoiz** [comment]
Hello Michael,

Thanks for your kind comment.
If you have WCS with distortion there are a couple of software that I know of, that do that kind of alignment.
One is [reproject](https://github.com/astropy/reproject) and the other is [MontagePy](https://pypi.org/project/MontagePy/). (This is a nice tutorial btw http://montage.ipac.caltech.edu/MontageNotebooks/Mosaic.html)

Hope this helps,
Martin.

**Comment by mworion** [comment]
Martin,
many thanks for the hints. Found there some entry point for trying out.
Michel
