### ISSUE TITLE
failed to install with pip

### ISSUE THREAD

**Issue by DSchmidlin** [toros-astro/astroalign#33]
OS: Windows 10 x64
command: pip install astroalign
output:

Building wheels for collected packages: sep
  Building wheel for sep (setup.py) ... error
  ERROR: Complete output from command 'c:\program files\python36\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\djschmi1\\AppData\\Local\\Temp\\pip-install-2ni6gba8\\sep\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\djschmi1\AppData\Local\Temp\pip-wheel-x1kosjxe' --python-tag cp36:
  ERROR: running bdist_wheel
  running build
  running build_ext
  building 'sep' extension
  error: [WinError 3] The system cannot find the path specified: 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\PlatformSDK\\lib'
  ----------------------------------------
  ERROR: Failed building wheel for sep
  Running setup.py clean for sep
Failed to build sep
Installing collected packages: sep, astroalign
  Running setup.py install for sep ... error
    ERROR: Complete output from command 'c:\program files\python36\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\djschmi1\\AppData\\Local\\Temp\\pip-install-2ni6gba8\\sep\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\djschmi1\AppData\Local\Temp\pip-record-6b0iy0b4\install-record.txt' --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_ext
    building 'sep' extension
    error: [WinError 3] The system cannot find the path specified: 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\PlatformSDK\\lib'
    ----------------------------------------
ERROR: Command "'c:\program files\python36\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\djschmi1\\AppData\\Local\\Temp\\pip-install-2ni6gba8\\sep\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\djschmi1\AppData\Local\Temp\pip-record-6b0iy0b4\install-record.txt' --single-version-externally-managed --compile" failed with error code 1 in C:\Users\djschmi1\AppData\Local\Temp\pip-install-2ni6gba8\sep\

**Comment by martinberoiz** [comment]
It seems the sep dependency fails to install on windows, thanks for pointing that out, I will look into it.

**Comment by martinberoiz** [comment]
can you confirm that

    pip install sep

fails in you windows environment? If so, I'd suggest opening an issue on the [sep repo](https://github.com/kbarbary/sep) as well.
