### ISSUE TITLE
_generate_invariants requires at least 5 sources to work, find_transform only 3.

### ISSUE THREAD

**Issue by RugiadaC** [toros-astro/astroalign#36]
I'm trying to run find_transform on a target image with 4 sources. The check on target_controlp is passed because there are at least 3 sources, but when it enters _generate_invariants the indx variable is forced to length=5(>4), since NUM_NEAREST_NEIGHBORS=5, and there is no check on this. Then the arrange function is not able to find the fifth source.
I'm attaching a screenshot of the errors.
![image](https://user-images.githubusercontent.com/31289992/64714132-76822600-d494-11e9-89bb-20b09dc300b3.png)

**Comment by martinberoiz** [comment]
Yes, this is definitely a bug.
I originally intended this to work with 3 sources or more.
I will add a new test for low number of sources and try to implement a solution, but it might take a while.
I'm afraid that for low number of sources I will have to treat it as a separate case.

**Comment by RugiadaC** [comment]
So does this mean that if being able to change NUM_NEAREST_NEIGHBORS to len(sources) if len(sources)<5 would not solve the problem?
This would be too bad because most of my data has a low number of sources :(

I was trying to do this but I have some scope problem:
![image](https://user-images.githubusercontent.com/31289992/64723381-d255aa80-d4a6-11e9-8879-feaa78c532fe.png)

**Comment by martinberoiz** [comment]
Instead of tweaking the source code, you can try changing the value before you call `register`, like this:

    import astroalign as aa
    aa.NUM_NEAREST_NEIGHBORS = 3 # (or 4)
    aligned = aa.register(source, target)

but I can't guarantee it will work.

The example you gave won't work because you're modifying the variable num instead of the variable NUM_NEAREST_NEIGHBORS.

**Comment by martinberoiz** [comment]
The new release 2.1 should work with few sources on the image. Please feel free to reopen this issue or open a new one if you still find problems.

[Check the new documentation out](https://astroalign.readthedocs.io/en/latest/examples.html)
