### ISSUE TITLE
test without sep installed

### ISSUE THREAD

**Issue by martinberoiz** [toros-astro/astroalign#4]
Make travis env to test without sep installed

**Comment by leliel12** [comment]
que es env?

**Comment by leliel12** [comment]
por ahi no entendi bien pero en tu tox.ini vi eso `pip install sep` por que `sep` no esta en la seccion deps de `[testenv]`

**Comment by martinberoiz** [comment]
env=environment
si, con el sep no se bien que hacer. Es una "dependencia" que no es necesaria, si esta la uso, y si no esta uso otro método casero. Pero pasa que sí la uso en los tests :/
Entonces quiero testear un environment donde no tenga sep instalado para estar seguro que defaultea al findsources casero y q anda bien

**Comment by leliel12** [comment]
ponela en "deps" que solo instala para el test env. Fijate que en corral si
encuentra ipython lo usa... sino se va al interprete clásico

On Mon, 25 Jan 2016 at 11:06 Martin Beroiz <notifications@github.com> wrote:

> env=environment
> si, con el sep no se bien que hacer. Es una "dependencia" que no es
> necesaria, si esta la uso, y si no esta uso otro método casero. Pero pasa
> que sí la uso en los tests :/
> Entonces quiero testear un environment donde no tenga sep instalado para
> estar seguro que defaultea al findsources casero y q anda bien
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/toros-astro/astroalign/issues/4#issuecomment-174518099>
> .
>
-- 

Juan BC (from phone)

**Comment by martinberoiz** [comment]
ahi me fijo como hiciste, gracias

**Comment by leliel12** [comment]
ponelo en deps de tox.ini


On Mon, 25 Jan 2016 at 13:24 Martin Beroiz <notifications@github.com> wrote:

> ahi me fijo como hiciste, gracias
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/toros-astro/astroalign/issues/4#issuecomment-174564524>
> .
>
-- 

Juan BC (from phone)
