### ISSUE TITLE
find_transform does not align the stars correctly

### ISSUE THREAD

**Issue by davidenitti** [toros-astro/astroalign#53]
I'm testing find_transform and it aligns the stars but often there is a misalignment of few pixels.
What can I do to improve the result?
an example of the difference of 2 aligned images. it should be black but you see double dots that are not aligned stars
![Screenshot from 2020-08-31 19-12-53](https://user-images.githubusercontent.com/7438184/91747280-2da01180-ebbe-11ea-9d14-0b5c5e86a744.png)

**Comment by martinberoiz** [comment]
That seems quite off-mark. First thing that comes to mind, is this a large field of view? In large FOV there could be non-linear distortions.

**Comment by davidenitti** [comment]
yes, it's a large FOV, any way to fit with such distortions?

**Comment by martinberoiz** [comment]
If they are truly non-linear, you can try with [reproject](https://reproject.readthedocs.io/en/stable/) or [MontagePy](https://github.com/Caltech-IPAC/Montage), they deal with non-linear distortions. But for both you need to know WCS of both images.

**Comment by martinberoiz** [comment]
I will close this issue. Let me know if problem arise again.
