### ISSUE TITLE
Add inversion test

### ISSUE THREAD

**Issue by martinberoiz** [toros-astro/astroalign#8]
If we calculate an affine transform t1 from image A to B, and transformation t2 from B to A, we can test wether a point p in A transforms to a point q in B using t1 and that point q will transform back to p (with errors) using t2.

**Comment by BrunoSanchez** [comment]
It would be needed sample data for ths issue?
I can provide

**Comment by martinberoiz** [comment]
yes, we need sample data, but I generate a simulated (random) sky for that and a known linear transformation, so no need for extra data files.
Check function ```test_find_affine_transform``` inside tests/test_align.py

**Comment by martinberoiz** [comment]
I kept the simulation quite simple, just for the purpose of testing, surely you know much better how to simulate more realistic data!
